import type { ProviderPreset, ModelPreset } from './types.js';

// ─── Provider Presets ────────────────────────────────────
export const providerPresets: ProviderPreset[] = [
  {
    id: 'openrouter',
    label: 'OpenRouter',
    endpoint: 'https://openrouter.ai/api/v1/chat/completions',
    authType: 'bearer',
    apiFormat: 'openai',
    enabled: true,
    aliases: ['openrouter', 'or'],
    credentialRef: 'openrouter',
    maxOutputTokens: 8192,
    speedClass: 'fast',
    qualityClass: 'frontier',
  },
  {
    id: 'groq',
    label: 'Groq Cloud',
    endpoint: 'https://api.groq.com/openai/v1/chat/completions',
    authType: 'bearer',
    apiFormat: 'openai',
    enabled: true,
    aliases: ['groq'],
    credentialRef: 'groq',
    maxOutputTokens: 8192,
    speedClass: 'very_fast',
    qualityClass: 'good',
  },
  {
    id: 'gemini',
    label: 'Google Gemini',
    endpoint: 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions',
    authType: 'bearer',
    apiFormat: 'openai',
    enabled: true,
    aliases: ['gemini', 'google'],
    credentialRef: 'gemini',
    maxOutputTokens: 8192,
    speedClass: 'fast',
    qualityClass: 'strong',
  },
  {
    id: 'cerebras',
    label: 'Cerebras',
    endpoint: 'https://api.cerebras.ai/v1/chat/completions',
    authType: 'bearer',
    apiFormat: 'openai',
    enabled: true,
    aliases: ['cerebras'],
    credentialRef: 'cerebras',
    maxOutputTokens: 8192,
    speedClass: 'very_fast',
    qualityClass: 'good',
  },
  {
    id: 'together',
    label: 'Together AI',
    endpoint: 'https://api.together.xyz/v1/chat/completions',
    authType: 'bearer',
    apiFormat: 'openai',
    enabled: true,
    aliases: ['together'],
    credentialRef: 'together',
    maxOutputTokens: 8192,
    speedClass: 'fast',
    qualityClass: 'strong',
  },
  {
    id: 'fireworks',
    label: 'Fireworks AI',
    endpoint: 'https://api.fireworks.ai/inference/v1/chat/completions',
    authType: 'bearer',
    apiFormat: 'openai',
    enabled: true,
    aliases: ['fireworks'],
    credentialRef: 'fireworks',
    maxOutputTokens: 8192,
    speedClass: 'fast',
    qualityClass: 'strong',
  },
  {
    id: 'deepinfra',
    label: 'DeepInfra',
    endpoint: 'https://api.deepinfra.com/v1/openai/chat/completions',
    authType: 'bearer',
    apiFormat: 'openai',
    enabled: true,
    aliases: ['deepinfra'],
    credentialRef: 'deepinfra',
    maxOutputTokens: 8192,
    speedClass: 'fast',
    qualityClass: 'good',
  },
  {
    id: 'novita',
    label: 'Novita AI',
    endpoint: 'https://api.novita.ai/v1/openai/chat/completions',
    authType: 'bearer',
    apiFormat: 'openai',
    enabled: true,
    aliases: ['novita'],
    credentialRef: 'novita',
    maxOutputTokens: 8192,
    speedClass: 'fast',
    qualityClass: 'good',
  },
  {
    id: 'hyperbolic',
    label: 'Hyperbolic',
    endpoint: 'https://api.hyperbolic.xyz/v1/chat/completions',
    authType: 'bearer',
    apiFormat: 'openai',
    enabled: true,
    aliases: ['hyperbolic'],
    credentialRef: 'hyperbolic',
    maxOutputTokens: 8192,
    speedClass: 'medium',
    qualityClass: 'good',
  },
  {
    id: 'sambanova',
    label: 'SambaNova',
    endpoint: 'https://api.sambanova.ai/v1/chat/completions',
    authType: 'bearer',
    apiFormat: 'openai',
    enabled: true,
    aliases: ['sambanova'],
    credentialRef: 'sambanova',
    maxOutputTokens: 8192,
    speedClass: 'fast',
    qualityClass: 'good',
  },
  {
    id: 'perplexity',
    label: 'Perplexity AI',
    endpoint: 'https://api.perplexity.ai/chat/completions',
    authType: 'bearer',
    apiFormat: 'openai',
    enabled: true,
    aliases: ['perplexity'],
    credentialRef: 'perplexity',
    maxOutputTokens: 8192,
    speedClass: 'medium',
    qualityClass: 'strong',
  },
  {
    id: 'nvidia_nim',
    label: 'NVIDIA NIM',
    endpoint: 'https://integrate.api.nvidia.com/v1/chat/completions',
    authType: 'bearer',
    apiFormat: 'openai',
    enabled: true,
    aliases: ['nvidia', 'nim'],
    credentialRef: 'nvidia_nim',
    maxOutputTokens: 8192,
    speedClass: 'slow',
    qualityClass: 'frontier',
  },
  {
    id: 'nebius',
    label: 'Nebius AI',
    endpoint: 'https://api.studio.nebius.ai/v1/chat/completions',
    authType: 'bearer',
    apiFormat: 'openai',
    enabled: true,
    aliases: ['nebius'],
    credentialRef: 'nebius',
    maxOutputTokens: 8192,
    speedClass: 'medium',
    qualityClass: 'strong',
  },
  {
    id: 'replicate',
    label: 'Replicate',
    endpoint: 'https://api.replicate.com/v1/chat/completions',
    authType: 'bearer',
    apiFormat: 'openai',
    enabled: true,
    aliases: ['replicate', 'rep'],
    credentialRef: 'replicate',
    maxOutputTokens: 8192,
    speedClass: 'medium',
    qualityClass: 'good',
  },
  {
    id: 'lambda',
    label: 'Lambda Labs',
    endpoint: 'https://api.lambdalabs.com/v1/chat/completions',
    authType: 'bearer',
    apiFormat: 'openai',
    enabled: true,
    aliases: ['lambda', 'lambdalabs'],
    credentialRef: 'lambda',
    maxOutputTokens: 8192,
    speedClass: 'medium',
    qualityClass: 'strong',
  },
  {
    id: 'custom_openai',
    label: 'Custom OpenAI-Compatible',
    endpoint: 'https://your-custom-endpoint.com/v1/chat/completions',
    authType: 'bearer',
    apiFormat: 'openai',
    enabled: true,
    aliases: ['custom'],
    credentialRef: 'custom_openai',
    maxOutputTokens: 8192,
    speedClass: 'medium',
    qualityClass: 'good',
  },
];

// ─── Model Presets ───────────────────────────────────────
export const modelPresets: ModelPreset[] = [
  // ── OpenRouter ──
  {
    id: 'or_gpt4o_mini',
    providerId: 'openrouter',
    title: 'GPT-4o Mini',
    model: 'openai/gpt-4o-mini',
    useAs: ['expert', 'judge', 'synthesis'],
    enabled: true,
    speedClass: 'fast',
    qualityClass: 'good',
    maxOutputTokens: 8192,
  },
  {
    id: 'or_claude3_haiku',
    providerId: 'openrouter',
    title: 'Claude 3 Haiku',
    model: 'anthropic/claude-3-haiku',
    useAs: ['expert', 'judge', 'synthesis'],
    enabled: true,
    speedClass: 'fast',
    qualityClass: 'good',
    maxOutputTokens: 8192,
  },
  {
    id: 'or_deepseek_v3',
    providerId: 'openrouter',
    title: 'DeepSeek V3',
    model: 'deepseek/deepseek-chat',
    useAs: ['expert', 'judge', 'synthesis'],
    enabled: true,
    speedClass: 'fast',
    qualityClass: 'strong',
    maxOutputTokens: 8192,
  },

  // ── Groq ──
  {
    id: 'groq_llama3_8b',
    providerId: 'groq',
    title: 'Llama 3 8B',
    model: 'llama3-8b-8192',
    useAs: ['expert'],
    enabled: true,
    speedClass: 'very_fast',
    qualityClass: 'basic',
    maxOutputTokens: 8192,
  },
  {
    id: 'groq_llama3_70b',
    providerId: 'groq',
    title: 'Llama 3 70B',
    model: 'llama3-70b-8192',
    useAs: ['expert', 'judge'],
    enabled: true,
    speedClass: 'very_fast',
    qualityClass: 'good',
    maxOutputTokens: 8192,
  },
  {
    id: 'groq_mixtral',
    providerId: 'groq',
    title: 'Mixtral 8x7B',
    model: 'mixtral-8x7b-32768',
    useAs: ['expert', 'judge'],
    enabled: true,
    speedClass: 'fast',
    qualityClass: 'good',
    maxOutputTokens: 32768,
  },
  {
    id: 'groq_llama_vision',
    providerId: 'groq',
    title: 'Llama 3.2 90B Vision',
    model: 'llama-3.2-90b-vision-preview',
    useAs: ['expert', 'judge'],
    enabled: true,
    speedClass: 'fast',
    qualityClass: 'strong',
    maxOutputTokens: 8192,
  },

  // ── Gemini ──
  {
    id: 'gemini_flash',
    providerId: 'gemini',
    title: 'Gemini 2.0 Flash',
    model: 'gemini-2.0-flash',
    useAs: ['expert', 'judge', 'synthesis'],
    enabled: true,
    speedClass: 'fast',
    qualityClass: 'strong',
    maxOutputTokens: 8192,
  },
  {
    id: 'gemini_pro',
    providerId: 'gemini',
    title: 'Gemini 2.0 Pro',
    model: 'gemini-2.0-pro',
    useAs: ['expert', 'judge', 'synthesis'],
    enabled: true,
    speedClass: 'medium',
    qualityClass: 'frontier',
    maxOutputTokens: 8192,
  },

  // ── Cerebras ──
  {
    id: 'cerebras_llama3_8b',
    providerId: 'cerebras',
    title: 'Llama 3.1 8B',
    model: 'llama3.1-8b',
    useAs: ['expert'],
    enabled: true,
    speedClass: 'very_fast',
    qualityClass: 'basic',
    maxOutputTokens: 8192,
  },

  // ── Together AI ──
  {
    id: 'tog_llama3_70b',
    providerId: 'together',
    title: 'Llama 3 70B',
    model: 'meta-llama/Llama-3-70b-chat-hf',
    useAs: ['expert', 'judge'],
    enabled: true,
    speedClass: 'fast',
    qualityClass: 'good',
    maxOutputTokens: 8192,
  },
  {
    id: 'tog_mixtral',
    providerId: 'together',
    title: 'Mixtral 8x22B',
    model: 'mistralai/Mixtral-8x22B-Instruct-v0.1',
    useAs: ['expert', 'judge'],
    enabled: true,
    speedClass: 'medium',
    qualityClass: 'strong',
    maxOutputTokens: 8192,
  },

  // ── Fireworks ──
  {
    id: 'fw_llama3_70b',
    providerId: 'fireworks',
    title: 'Llama 3 70B',
    model: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
    useAs: ['expert', 'judge'],
    enabled: true,
    speedClass: 'fast',
    qualityClass: 'good',
    maxOutputTokens: 8192,
  },

  // ── DeepInfra ──
  {
    id: 'di_llama3_70b',
    providerId: 'deepinfra',
    title: 'Llama 3 70B',
    model: 'meta-llama/Meta-Llama-3-70B-Instruct',
    useAs: ['expert', 'judge'],
    enabled: true,
    speedClass: 'fast',
    qualityClass: 'good',
    maxOutputTokens: 8192,
  },

  // ── Perplexity ──
  {
    id: 'pplx_sonar',
    providerId: 'perplexity',
    title: 'Sonar Small 32K',
    model: 'sonar-small-chat',
    useAs: ['expert'],
    enabled: true,
    speedClass: 'fast',
    qualityClass: 'good',
    maxOutputTokens: 8192,
  },
  {
    id: 'pplx_sonar_large',
    providerId: 'perplexity',
    title: 'Sonar Large 32K',
    model: 'sonar-large-chat',
    useAs: ['expert', 'judge', 'synthesis'],
    enabled: true,
    speedClass: 'medium',
    qualityClass: 'strong',
    maxOutputTokens: 8192,
  },
];
